version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
      args:
        REACT_APP_GOOGLE_APP_CLIENT_ID: ${REACT_APP_GOOGLE_APP_CLIENT_ID}
        REACT_APP_GITHUB_APP_CLIENT_ID: ${REACT_APP_GITHUB_APP_CLIENT_ID}
        REACT_APP_OPENVIDU_SERVER_URL: ${REACT_APP_OPENVIDU_SERVER_URL}
        REACT_APP_OPENVIDU_SERVER_SECRET: ${REACT_APP_OPENVIDU_SERVER_SECRET}
    container_name: free_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: free_nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: free_backend
    volumes:
      - ./backend:/app
